[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_test = "AwVPCWBAwYgVrmC4CPmhaY1skNmuZSgqwMoLy1nDtJxT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/miquel/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
